### ISSUE TITLE
Postgresql adapter always recreates tables during initialization

### ISSUE THREAD

**Issue by georgiuk** [Missionware/cognibase-public#6]
Table name includes double quotes in class map and considers it as non existent during initialization. 
Should the following be with quotes??:
```csharp
AdjustTableName
AdjustColumnName
```

**Comment by vgaitano** [comment]
**schemaHash.ContainsKey(tblName)** was used to check for existence of tables on initialization.
The enumeration of Table Names was based on 'ooClassMap.SchemaRequiredTableNames' which is in the form appropriate to be included in queries.
Replaced by enumeration based on 'ooClassMap.SchemaRequiredTableNamesAsValues'
